### ISSUE TITLE
Why do you use...

### ISSUE THREAD

**Issue by Burnfaker** [mk-fg/dracut-crypt-sshd#5]
dropbearconvert openssh dropbear "${dropbear_rsa_key}"{.tmp,} >/dev/null 2>&1\

i think we need this file in /etc/dropbear. 
dropbearconvert openssh dropbear "${dropbear_rsa_key}"{.tmp,} /etc/dropbear/WhatElse.pub

**Comment by mk-fg** [comment]
Isn't that what `inst "${dropbear_rsa_key}" /etc/dropbear/host_key` [does](https://github.com/mk-fg/dracut-crypt-sshd/blob/master/60dropbear-sshd/module-setup.sh#L66) just a few lines later?

**Comment by Burnfaker** [comment]
Sure, but i can't see this file /etc/dropbear/host_key.
I will tell you after i found a problem or solution why don't create a host_key file

**Comment by mk-fg** [comment]
Prehaps a bit too obvious, but please note that it should only appear inside dracut image, not in /etc of the OS you're running dracut on.
And I think if "inst" (it's a dracut function) fails, whole dracut image-building process will abort, or at least print some really noticeable error message, so I strongly suspect that you just might be looking for that file in a wrong place.

**Comment by mk-fg** [comment]
Guess this should be resolved by now, one way or the other.

Also, for such basic issues (network doesn't work, can't find host_key file, etc), if you're not sure about how to debug it and where to look at all, I think IRC might be a way better way to communicate than offline messaging here.
I'm MK_FG on freenode/oftc, always online there (via [znc](http://znc.in)).
